# Generated by Django 2.1.7 on 2019-04-25 21:06

import cliente.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=75, verbose_name='Apellidos')),
                ('direccion', models.CharField(default='Ciudad', max_length=125, verbose_name='Direccion')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Ingrese solamente numeros', regex='^[0-9]*$'), cliente.models.numeroTelefono], verbose_name='Telefono')),
                ('nit', models.CharField(default='C/F', max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese un NIT Valido', regex='^[0-9 C,F,/,c,f,]*$')], verbose_name='No. de NIT')),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('Especial', 'Especial'), ('Mayorista', 'Mayorista')], default='Normal', max_length=15, verbose_name='Tipo de Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(editable=False, verbose_name='saldo')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
