# Generated by Django 2.1.7 on 2019-04-25 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('producto', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('despacho', models.BooleanField(blank=True, default=False, verbose_name='Despachado')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0, editable=False, verbose_name='Total')),
                ('abono', models.FloatField(default=0, verbose_name='Abono')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('entrega', models.DateField(default=datetime.date.today, verbose_name='Fecha de Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Cliente')),
                ('tipo_pago', models.ManyToManyField(default=0, to='core.TipoPago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='Pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden.Pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='item',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto', verbose_name='Producto'),
        ),
    ]
